// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPUJQcG6d5ayC6rc5tMAWn6UUbiEC66zI',
    appId: '1:1050782929738:web:276854e095585b19fba7b3',
    messagingSenderId: '1050782929738',
    projectId: 'fluttermobile-77956',
    authDomain: 'fluttermobile-77956.firebaseapp.com',
    storageBucket: 'fluttermobile-77956.firebasestorage.app',
    measurementId: 'G-ZL2LY4FBEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHnoQyVZwYDNcSc1JsFGChWxxeNqTaEkA',
    appId: '1:1050782929738:android:f12fdd2ad4583b56fba7b3',
    messagingSenderId: '1050782929738',
    projectId: 'fluttermobile-77956',
    storageBucket: 'fluttermobile-77956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmA82GiU5zOSPyMHVSTXaITgMa4x1nNo',
    appId: '1:1050782929738:ios:a68ecb8e4ba94a36fba7b3',
    messagingSenderId: '1050782929738',
    projectId: 'fluttermobile-77956',
    storageBucket: 'fluttermobile-77956.firebasestorage.app',
    iosBundleId: 'com.example.flutterMobilePpks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmA82GiU5zOSPyMHVSTXaITgMa4x1nNo',
    appId: '1:1050782929738:ios:a68ecb8e4ba94a36fba7b3',
    messagingSenderId: '1050782929738',
    projectId: 'fluttermobile-77956',
    storageBucket: 'fluttermobile-77956.firebasestorage.app',
    iosBundleId: 'com.example.flutterMobilePpks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPUJQcG6d5ayC6rc5tMAWn6UUbiEC66zI',
    appId: '1:1050782929738:web:1770a894e6df8ed4fba7b3',
    messagingSenderId: '1050782929738',
    projectId: 'fluttermobile-77956',
    authDomain: 'fluttermobile-77956.firebaseapp.com',
    storageBucket: 'fluttermobile-77956.firebasestorage.app',
    measurementId: 'G-KTQW1GTN22',
  );

}